# Generated by Django 2.1.4 on 2018-12-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_sale',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
