# Generated by Django 2.1.4 on 2018-12-16 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20181216_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_sale',
            name='datetime',
        ),
        migrations.AddField(
            model_name='item_sale',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
