# Generated by Django 2.1.4 on 2018-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20181216_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('purchase_quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('kitchen_issue', models.DecimalField(decimal_places=3, max_digits=5)),
                ('stock', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
