# Generated by Django 2.1.4 on 2018-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_item_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_purchase',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
