# Generated by Django 2.1.4 on 2018-12-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_item_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_sale',
            name='item_hospital',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
