# Generated by Django 2.1.4 on 2018-12-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_item_sale_item_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_sale',
            old_name='item_hospital',
            new_name='hospital',
        ),
        migrations.AddField(
            model_name='item_purchase',
            name='hospital',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
