# Generated by Django 2.1.4 on 2018-12-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20181217_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_purchase',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
