# Generated by Django 2.1.4 on 2018-12-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_item_purchase_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_purchase',
            name='kitchen_issue',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item_purchase',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
